version: 2.1

commands:
  id:
    steps:        
      - run: echo ${CIRCLE_WORKFLOW_ID}
    

jobs:

  testCommand:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - id

      

workflows:
  welcome:
    jobs: 
      - testCommand