version: 2.1
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: echo "This is pipeline ID << pipeline.id >>"
    steps:
      - run: echo << parameters.to >>

jobs:

  testCommand:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - sayhello

      

workflows:
  welcome:
    jobs: 
      - testCommand